#!/usr/bin/env python3
"""P3-5 — what `confidence` means, and where the number comes from.

§5.3 requires `confidence` to be "calibrated in the sense that it is comparable across
lanes". Here that is made literal: **confidence is this lane's estimated probability that
its answer is correct**, measured on `order_lines_train.csv`. A 0.95 from the barcode lane
and a 0.95 from the lexical lane then mean the same thing, and a threshold on confidence
means one thing rather than four.

Three choices worth defending.

**Pooled by mechanism, not per reason code.** `alias_exact`, `barcode_unique` and
`alias_exact_superseded_redirect` all say the same thing - an exact identifier, checked for
uniqueness and normalised through supersession. Their individual rates (23/23, 12/12,
41/41) differ only by noise, and estimating each from a dozen observations would publish
sampling error as if it were signal.

**Laplace, not the raw fraction.** `(correct + 1) / (n + 2)`. The exact-identifier pool is
76 for 76; publishing 1.000 would claim error is impossible, which no sample of 76 can
support. Laplace never returns 0 or 1 and shrinks toward 0.5 as n falls, which is the
behaviour a small sample deserves.

**The interval is reported, not hidden.** The exact-identifier pool has a one-sided 95%
lower bound of 96.6%, clearing the 92.68% break-even. The lexical pool's is **90.2%** - it
straddles break-even. At n=43 we cannot yet *prove* the lexical lane pays, even though it
measures 97.7%. That is a fact about 420 labelled lines, not about the lane, and it belongs
next to the number rather than behind it. See `EVAL.md`.

Regenerate with:

    python3 -m src.matching.calibration --write

The table is committed so the matcher stays deterministic and offline; the script is
committed so the numbers can be re-derived rather than trusted. Nothing here feeds a
decision - the arbitration gates use raw similarity scores - so calibrating on train
introduces no feedback loop into what the matcher chooses.
"""
from __future__ import annotations

import argparse
import pathlib

# --- generated by `python3 -m src.matching.calibration --write`; do not hand-edit -------
# reason_code -> (pool, confidence, pool_correct, pool_n, pool_wilson_lower_95)
CALIBRATION: dict[str, tuple[str, float, int, int, float]] = {
    "alias_exact":                     ("exact_identifier", 0.9872, 76, 76, 0.9656),
    "alias_exact_superseded_redirect": ("exact_identifier", 0.9872, 76, 76, 0.9656),
    "barcode_unique":                  ("exact_identifier", 0.9872, 76, 76, 0.9656),
    "lexical_unique":                  ("lexical_separated", 0.9556, 42, 43, 0.9022),
}
# --- end generated ---------------------------------------------------------------------

POOLS = {
    "exact_identifier": ["alias_exact", "alias_exact_superseded_redirect", "barcode_unique"],
    "lexical_separated": ["lexical_unique"],
}

# Used only until a lane has been measured - a new lane must not silently inherit a
# neighbour's confidence. Deliberately below break-even so an uncalibrated lane cannot be
# mistaken for one that pays.
UNCALIBRATED = 0.50


def confidence_for(reason_code: str) -> float:
    return CALIBRATION.get(reason_code, ("", UNCALIBRATED))[1]


def _laplace(correct: int, n: int) -> float:
    return (correct + 1) / (n + 2)


def _measure() -> dict:
    import collections
    import sys

    root = pathlib.Path(__file__).resolve().parents[2]
    sys.path.insert(0, str(root))
    sys.path.insert(0, str(root / "_work" / "probes"))
    from p05_objective import wilson_lower  # noqa: E402
    from src.eval import harness  # noqa: E402

    outs = harness.run(harness.build("pipeline"), harness.load("order_lines_train.csv"))
    per_code: dict = collections.defaultdict(lambda: [0, 0])
    for o in outs:
        if o.decision.decision == "auto":
            per_code[o.decision.reason_code][0 if o.tp else 1] += 1

    table = {}
    for pool, codes in POOLS.items():
        correct = sum(per_code[c][0] for c in codes)
        n = correct + sum(per_code[c][1] for c in codes)
        if not n:
            continue
        conf, lo = round(_laplace(correct, n), 4), round(wilson_lower(correct / n, n), 4)
        for c in codes:
            table[c] = (pool, conf, correct, n, lo)
    unmeasured = set(per_code) - set(table)
    if unmeasured:
        raise SystemExit(f"lane(s) answering but not in any pool: {sorted(unmeasured)}")
    return table


def _main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="rewrite the table in this file")
    args = ap.parse_args()

    from src.eval.metrics import BREAK_EVEN_P

    table = _measure()
    print(f"=== measured on order_lines_train.csv (break-even {BREAK_EVEN_P:.2%}) ===")
    print(f"  {'pool':<20}{'correct/n':>12}{'raw':>9}{'confidence':>12}{'95% lower':>11}")
    for pool in POOLS:
        row = next((v for v in table.values() if v[0] == pool), None)
        if not row:
            continue
        _, conf, c, n, lo = row
        flag = "" if lo >= BREAK_EVEN_P else "   <-- interval straddles break-even"
        print(f"  {pool:<20}{f'{c}/{n}':>12}{c / n:>9.1%}{conf:>12.4f}{lo:>11.1%}{flag}")

    if not args.write:
        drift = {k: (v, CALIBRATION.get(k)) for k, v in table.items() if CALIBRATION.get(k) != v}
        print(f"\n  committed table is {'STALE' if drift else 'current'}")
        for k, (new, old) in drift.items():
            print(f"    {k}: committed {old} -> measured {new}")
        return

    src = pathlib.Path(__file__)
    text = src.read_text(encoding="utf-8")
    body = "\n".join(
        f'    {k + chr(58):<35}{v!r},'.replace("(", "(").replace("'", '"', 2)
        for k, v in sorted(table.items()))
    start = text.index("CALIBRATION: dict")
    start = text.index("{", start)
    end = text.index("}\n# --- end generated", start)
    src.write_text(text[:start] + "{\n" + body + "\n" + text[end:], encoding="utf-8")
    print(f"\n  wrote {len(table)} entries into {src.name}")


if __name__ == "__main__":
    _main()
